### ISSUE TITLE
how to setup config files in volumes seen by shinyproxy docker

### ISSUE THREAD

**Issue by ConYel** [openanalytics/shinyproxy-docker#1]
Hello and thank you for this very useful tool!

I am having trouble to connect to shinyproxy when I try to use a "users.yml" file and authentication "simple".
I run the docker with volumes: 
```
 -v ./application.yml:/opt/shinyproxy/application.yml -v ./users.yml:/opt/shinyproxy/users.yml -v logo.png:/opt/shinyproxy/logo.png  docker.io/openanalytics/shinyproxy:3.0.2
```
in the application.yml I have put:
```
spring:
  config:
    import:
     - ./users.yml
proxy:
  title: Shiny Proxy Apps
  logo-url: ./logo.png
```
Are the volumes wrongly pointed? or is there any other way to configure it?
